name: Build Search Index

on:
  workflow_dispatch:
  schedule:
    - cron: "5 8,13,18 * * *"

jobs:
  index:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: tools
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with: 
          node-version: 19.x
      - name: Install dependencies
        run: npm ci
      - name: Indexing
        run: npm run index
      - name: Log allograph types in each inscription
        run: npm run inscriptions-allograph-types
      - name: Generate allograph type pages
        run: node gen-allo-type-pages.mjs
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated annotations indexing
